### ISSUE TITLE
Jupyter Notebook blank

### ISSUE THREAD

**Issue by KwatMDPhD** [joshday/PlotlyLight.jl#4]
<img width="1107" alt="Screen Shot 2022-02-10 at 09 34 58" src="https://user-images.githubusercontent.com/7741548/153453031-fc93b508-1997-4d48-9960-82b2b37f14bb.png">
<img width="905" alt="Screen Shot 2022-02-10 at 09 35 18" src="https://user-images.githubusercontent.com/7741548/153453073-9d33ba3d-af7d-4183-85c2-26c09b46bbcf.png">

**Comment by KwatMDPhD** [comment]
No rush.

<img width="1325" alt="Screen Shot 2022-02-10 at 10 47 20" src="https://user-images.githubusercontent.com/7741548/153466217-68711f7b-54c6-42c4-9ee8-ac4c5223a09f.png">

**Comment by joshday** [comment]
Apparently Jupyter does more magic behind the scenes than Pluto.jl does.  I don't have an immediate fix but I want to figure this one out.

**Comment by KwatMDPhD** [comment]
Sounds good. Thanks for looking into this. It would be great if, by default and until the fix arrives, to just show string representation? So the windows don't blow up. 

By the way, do you recommend any jupyter alternative?

**Comment by joshday** [comment]
> By the way, do you recommend any jupyter alternative?

I highly recommend Pluto!  https://github.com/fonsp/Pluto.jl

**Comment by KwatMDPhD** [comment]
I think what you have is already a beautiful, minimal package. Carrying extra code just for jupyter seems not worth it :) Feel free to close this.

**Comment by KwatMDPhD** [comment]
I switched out of jupyter. Please don't do this just for 1 demand. Feel free to close this :)

**Comment by KwatMDPhD** [comment]
I think jupyter will slowly decay as pluto and other simpler things rise.

**Comment by joshday** [comment]
Will do!
