### ISSUE TITLE
Dark theme issue

### ISSUE THREAD

**Issue by KwatMDPhD** [joshday/PlotlyLight.jl#5]
Working around #4, with `display`, I am able to plot :)

<img width="1144" alt="Screen Shot 2022-02-10 at 09 37 58" src="https://user-images.githubusercontent.com/7741548/153453987-a93d8e49-723a-4837-bede-5949a53a74da.png">

However `plotly_dark` seems to not work

<img width="725" alt="Screen Shot 2022-02-10 at 09 38 03" src="https://user-images.githubusercontent.com/7741548/153453798-60339c9e-8e1f-452b-8641-8b2a572514ba.png">

What am I doing wrong?

**Comment by KwatMDPhD** [comment]
Gotcha. Thanks :) I wonder if there is a way to incorporate this into `min.js` Feel free to close this if you don't want to add theme feature.

**Comment by joshday** [comment]
If adding themes is as easy as parsing some JSON, it'd be cool to have.  Looks like they are generated by python code now (https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/templategen/definitions.py).  I'll keep this open for now.

**Comment by joshday** [comment]
Python's themes are now included as artifacts 🎉 .  Release pending.  See README for details.
